### ISSUE TITLE
Make a Timeline and Project Plan sheet with all of our output and milestones

### ISSUE THREAD

**Issue by lourdesvera** [edgi-govdata-archiving/EEW_Planning#353]
notebooks, event accessibility plans, etc.

- [x] Create a document with timeline and list of outcomes 
- [x] https://docs.google.com/spreadsheets/d/1-mQqLW3kMdSzuym82joAmR1WGjpEdchEWGfOLqI_yBc/edit?usp=sharing
- [x] Circulate document
- [x] Edit and save

related to #351

**Comment by lourdesvera** [comment]
@Frijol @lesliealanis anybody want to jump on this with me?

**Comment by lesliealanis** [comment]
@lourdesvera I can help with this!
