### ISSUE TITLE
Set up management structures & explicit responsibilities around summer research assistants

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW_Planning#90]
We can do this at least partially through [management structure design workshops](https://docs.google.com/document/d/1AGaVa6Qkdg21oTLbxSm_zEDOFnKt2tLyqvpZmeQ8TD0/edit#heading=h.9d23dis9tmfj)

* [x] Management Workshop: Orientation to purpose https://github.com/edgi-govdata-archiving/EEW_Planning/issues/137
* [x] Management Workshop: Day-to-day prioritization and collaboration https://github.com/edgi-govdata-archiving/EEW_Planning/issues/138
* [x] Management Workshop: Adjustment and dynamic balancing https://github.com/edgi-govdata-archiving/EEW_Planning/issues/139
* [x] Management Workshop: Bringing it all together https://github.com/edgi-govdata-archiving/EEW_Planning/issues/140

Using this mural board: https://app.mural.co/invitation/mural/managementworkshops7524/1590099639425?sender=ifoundthemeaningoflife6546&key=93195d7a-8e7d-4ec6-a5b7-b4fed6f7bcb2 

┆Issue is synchronized with this [Trello card](https://trello.com/c/hyWdQQrV)

**Comment by Frijol** [comment]
For this week: schedule times for this.

**Comment by lourdesvera** [comment]
This also is dependent on: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/91

**Comment by lourdesvera** [comment]
@Frijol can I assign you to this too? and let's plan those management structure design workshops?

**Comment by Frijol** [comment]
Yep! Here's a when2meet: https://www.when2meet.com/?9152866-jyNUy

**Comment by Frijol** [comment]
Finished workshops, would like to continue to revisit as we go
